config/routes.rb
# == Route Map
#
#                        Prefix Verb     URI Pattern                                                                              Controller#Action
#                   rails_admin          /admin                                                                                   RailsAdmin::Engine
#              new_user_session GET      /users/sign_in(.:format)                                                                 devise/sessions#new
#                  user_session POST     /users/sign_in(.:format)                                                                 devise/sessions#create
#          destroy_user_session DELETE   /users/sign_out(.:format)                                                                devise/sessions#destroy
# user_slack_omniauth_authorize GET|POST /users/auth/slack(.:format)                                                              users/omniauth_callbacks#passthru
#  user_slack_omniauth_callback GET|POST /users/auth/slack/callback(.:format)                                                     users/omniauth_callbacks#slack
#      cancel_user_registration GET      /users/cancel(.:format)                                                                  registrations#cancel
#         new_user_registration GET      /users/sign_up(.:format)                                                                 registrations#new
#        edit_user_registration GET      /users/edit(.:format)                                                                    registrations#edit
#             user_registration PATCH    /users(.:format)                                                                         registrations#update
#                               PUT      /users(.:format)                                                                         registrations#update
#                               DELETE   /users(.:format)                                                                         registrations#destroy
#                               POST     /users(.:format)                                                                         registrations#create
#                          root GET      /                                                                                        messages#index
#     personality_insights_user GET      /users/:id/personality_insights(.:format)                                                users#personality_insights
#               dashboards_user GET      /users/:id/dashboards(.:format)                                                          users#dashboards
#                         users GET      /users(.:format)                                                                         users#index
#                               POST     /users(.:format)                                                                         users#create
#                      new_user GET      /users/new(.:format)                                                                     users#new
#                     edit_user GET      /users/:id/edit(.:format)                                                                users#edit
#                          user GET      /users/:id(.:format)                                                                     users#show
#                               PATCH    /users/:id(.:format)                                                                     users#update
#                               PUT      /users/:id(.:format)                                                                     users#update
#                               DELETE   /users/:id(.:format)                                                                     users#destroy
#               search_messages GET      /messages/search(.:format)                                                               messages#search
#                      messages GET      /messages(.:format)                                                                      messages#index
#                               POST     /messages(.:format)                                                                      messages#create
#                   new_message GET      /messages/new(.:format)                                                                  messages#new
#                  edit_message GET      /messages/:id/edit(.:format)                                                             messages#edit
#                       message GET      /messages/:id(.:format)                                                                  messages#show
#                               PATCH    /messages/:id(.:format)                                                                  messages#update
#                               PUT      /messages/:id(.:format)                                                                  messages#update
#                               DELETE   /messages/:id(.:format)                                                                  messages#destroy
#                         likes POST     /likes(.:format)                                                                         likes#create
#                          like DELETE   /likes/:id(.:format)                                                                     likes#destroy
#                                        /cable                                                                                   #<ActionCable::Server::Base:0x00007fc7f7ca3bb0 @mutex=#<Monitor:0x00007fc7f7ca3b88 @mon_owner=nil, @mon_count=0, @mon_mutex=#<Thread::Mutex:0x00007fc7f7ca3b38>>, @pubsub=nil, @worker_pool=nil, @event_loop=nil, @remote_connections=nil>
#            rails_service_blob GET      /rails/active_storage/blobs/:signed_id/*filename(.:format)                               active_storage/blobs#show
#     rails_blob_representation GET      /rails/active_storage/representations/:signed_blob_id/:variation_key/*filename(.:format) active_storage/representations#show
#            rails_disk_service GET      /rails/active_storage/disk/:encoded_key/*filename(.:format)                              active_storage/disk#show
#     update_rails_disk_service PUT      /rails/active_storage/disk/:encoded_token(.:format)                                      active_storage/disk#update
#          rails_direct_uploads POST     /rails/active_storage/direct_uploads(.:format)                                           active_storage/direct_uploads#create
#
# Routes for RailsAdmin::Engine:
#   dashboard GET         /                                      rails_admin/main#dashboard
#       index GET|POST    /:model_name(.:format)                 rails_admin/main#index
#         new GET|POST    /:model_name/new(.:format)             rails_admin/main#new
#      export GET|POST    /:model_name/export(.:format)          rails_admin/main#export
# bulk_delete POST|DELETE /:model_name/bulk_delete(.:format)     rails_admin/main#bulk_delete
# bulk_action POST        /:model_name/bulk_action(.:format)     rails_admin/main#bulk_action
#        show GET         /:model_name/:id(.:format)             rails_admin/main#show
#        edit GET|PUT     /:model_name/:id/edit(.:format)        rails_admin/main#edit
#      delete GET|DELETE  /:model_name/:id/delete(.:format)      rails_admin/main#delete
# show_in_app GET         /:model_name/:id/show_in_app(.:format) rails_admin/main#show_in_app

Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks', registrations: 'registrations' }

  root to: 'messages#index'
  # devise_scope :user do
  #   root to: "devise/sessions#new"
  # end

  resources :users do
    member do
      get :personality_insights
      get :dashboards
    end
  end

  resources :messages do
    collection do
      get :search
      # get :full_text
      # get :message_cloud
    end
  end

  resources :likes, only: %i[create destroy]

  mount ActionCable.server => '/cable'
end

app/models/message.rb
# == Schema Information
#
# Table name: messages
#
#  id           :bigint(8)        not null, primary key
#  sender_id    :integer
#  recipient_id :integer
#  body         :text
#  created_at   :datetime         not null
#  updated_at   :datetime         not null
#  likes_count  :integer
#

class Message < ApplicationRecord
  # Message ModelからはUser Modelを(.userメソッドではなく)sender or recipient メソッドで参照
  # messagesテーブルの外部キーはsender_id or recipient_id フィールド
  belongs_to :sender, foreign_key: :sender_id, class_name: 'User', inverse_of: :messages
  belongs_to :recipient, foreign_key: :recipient_id, class_name: 'User', inverse_of: :messages

  has_rich_text :body

  has_many :likes, dependent: :delete_all

  max_paginates_per 15

  validates :recipient, presence: true
  validates :body, presence: true

  scope :send_messages, ->(user_id) do
    where(sender_id: user_id).where.not(recipient_id: nil)
  end

  scope :date_limit, ->(date) do
    where("created_at <= ?", date)
  end

  scope :recipient_messages, ->(user_id) do
    where(recipient_id: user_id).where.not(sender_id: nil)
  end

  # scopeは長い条件文を省略するために使用
  scope :involving, ->(user) do
    where("messages.sender_id = :q OR messages.recipient_id = :q", q: user.id)
  end

  scope :between, ->(sender_id, recipient_id) do
    where("(messages.sender_id = ? AND messages.recipient_id =?) OR (messages.sender_id = ? AND messages.recipient_id =?)", sender_id, recipient_id, recipient_id, sender_id)
  end

  def like_user(user_id)
    likes.find_by(user_id: user_id)
  end

  def likes_users_name
    User.where(id: self.likes.pluck(:user_id)).pluck(:name).join(', ')
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action :authenticate_user!, only: %i[new index search create]
  before_action :set_messages, only: %i[index search]
  before_action :set_users, only: %i[new index search]

  def index; end

  def search
    # a_user_id にするのは 検索urlの場合は パラメータのpageの前に来ないとInfiniteScrollはうまく作動したため
    if (@user_id = params[:a_user_id])
      if params[:button] == 'sender'
        @messages = @messages.send_messages(@user_id)
      else
        @messages = @messages.recipient_messages(@user_id)
      end
    end

    render 'index'
  end

  def new
    render layout: false
  end

  def create
    @message = Message.new(massage_params)
    @message.recipient_id = params[:recipient_id]
    @message[:body] = @message.body.to_plain_text

    # ActionCable.server.broadcast 'message_channel', message: render_message(@message) if @message.save!

    if @message.save!
      redirect_to messages_path
      # # create.js.erb　が実行される
      # respond_to do |format|
      #   format.js
      # end
    end
  end

  def destroy
    @message = Message.find(params[:id])
    if @message.destroy
      flash[:notice] = "メッセージを削除しました!"
      redirect_to messages_path
    else
      render json: { message: @message.errors.full_messages.join(", ") }
    end
  end

  # def full_text
  #   message = Message.all.pluck(:body)
  #
  #   @messages = shellesc(message.join(',').delete("'").delete('"'))
  #
  #   render layout: false
  # end

  private

  # def shellesc(str, opt = {})
  #   str = str.dup
  #   if opt[:erace]
  #     opt[:erace] = [opt[:erace]] unless Array === opt[:erace]
  #     opt[:erace].each do |i|
  #       case i
  #       when :ctrl then
  #         str.gsub!(/[\x00-\x08\x0a-\x1f\x7f]/, '')
  #       when :hyphen then
  #         str.gsub!(/^-+/, '')
  #       else
  #         str.gsub!(i, '')
  #       end
  #     end
  #   end
  #   str.gsub!(/[\!\"\$\&\'\(\)\*\,\:\;\<\=\>\?\[\\\]\^\`\{\|\}\t ]/, '\\\\\\&')
  #   str
  # end

  def massage_params
    params.require(:message).permit(:body, :sender_id)
  end

  def render_message(message)
    ApplicationController.renderer.render(partial: 'messages/message', locals: { message: message, current_user: current_user || { id: '' } })
  end

  def set_users
    @users = User.where(archived: false)
  end

  def set_messages
    @current_user_id = current_user&.id
    # @messages = Message.send_messages(current_user).or(Message.date_limit('20210101')).includes(:sender, :recipient, :rich_text_body).order('updated_at DESC').page(params[:page]).without_count
    @messages = Message.includes(:sender, :recipient, :rich_text_body).order('updated_at DESC').page(params[:page]).without_count
  end
end

app/helpers/messages_helper.rb
module MessagesHelper
  def markdown(text)
    renderer = Redcarpet::Render::HTML.new(hard_wrap: true, filter_html: true)
    options = {
      autolink: true,
      no_intra_emphasis: true,
      fenced_code_blocks: true,
      lax_html_blocks: true,
      strikethrough: true,
      superscript: false,
      tables: true,
      space_after_headers: true,
      hard_wrap: true,
      xhtml: true,
      underline: true,
      highlight: true,
      link_attributes: { rel: 'nofollow', target: "_blank" },
    }
    Redcarpet::Markdown.new(renderer, options).render(text).html_safe
  end
end

app/views/messages/_message.html.erb
<div class="item-box">
  <ol class="steps">
    <li class="current left">
      <% if message.sender&.provider %>
        <% if message.sender&.image %>
          <%= image_tag message.sender&.image, class: 'img-rounded media-object profile-1 img-rounded pull-left', loading: 'lazy' %>
        <% end %>

        <strong class="pull-right">
          <%= message.sender&.name %>
        </strong>
      <% else %>
        <%= message.sender&.email %>
      <% end %>

      <i class="fa fa-heart fa-lg heart"></i>
    </li>

    <li class="current right">
      <% if message.recipient&.provider %>
        <% if message.recipient&.image %>
          <%= image_tag message.recipient&.image, class: 'img-rounded media-object profile-1 img-rounded pull-right', loading: 'lazy' %>
        <% end %>

        <strong>
          <%= message.recipient&.name %>
        </strong>
      <% else %>
        <i class="fa fa-envelope fa-3x pull-right" aria-hidden="true"></i>
        <strong>
          <%= message.recipient&.email %>
        </strong>
      <% end %>
    </li>
  </ol>

  <div class="detail">
    <%== message.body.presence || message[:body].gsub(/\n/, '<br>') %>
  </div>

  <div class="detail clearfix">
    <div class="pull-left">
      <% if message.like_user(@current_user_id) %>
        <button id="like-button" class="btn btn-default btn-xs decrement js-like-button" data-message-id="<%= message.id %>" data-toggle="tooltip" data-placement="top" title="<%= message.likes_users_name %>">
          <%= image_tag "icon_heart_red.svg", :size => "14x14" %>
          <span id="like-sum" class="js-like-sum">
              <%= message.likes.count %>
            </span>
        </button>
      <% else %>
        <button id="like-button" class="btn btn-default btn-xs increment js-like-button" data-message-id="<%= message.id %>" data-toggle="tooltip" data-placement="top" title="<%= message.likes_users_name %>">
          <%= image_tag "icon_heart.svg", :size => "14x14" %>
          <span id="like-sum" class="js-like-sum">
              <%= message.likes.count %>
            </span>
        </button>
      <% end %>
    </div>

    <span class="pull-right">
      <% if current_user.present? %>
        <% if current_user.id == message.sender&.id %>
        <span class="label label-primary">From me</span>
        <% end %>
        <% if current_user.id == message.recipient&.id %>
        <span class="label label-danger">To me</span>
        <% end %>
        <span class="hidden-xs"><%= message.updated_at.strftime("%Y年%-m月%-d日 %H:%M") %></span>
        <%= distance_of_time_in_words_to_now(message.updated_at) %>前

        <% if current_user.id == message.sender&.id %>
          <%= link_to message, method: :delete, class: "btn btn-danger btn-xs", data: { confirm: "Are you sure?", disable_with: "<i class='fa fa-spinner fa-spin'></i>" } do %>
          <i class="fa fa-trash"></i>
          <% end %>
        <% end %>
      <% end %>
    </span>

    <div class="clearfix"></div>
  </div>
</div>

<script>
  $(function() {
    $('.js-like-button').tooltip();
  });
</script>

app/views/messages/create.js.erb
// 先頭に足す _message.html.erb to #message
// messages/_message　をrender
// _message.html.erb内のmessageは@message
$('#messages').prepend("<%= j(render @message)%>");
$('#format-modal').modal('hide');
// メッセージの入力欄を空にする
$('#new_message')[0].reset();

app/views/messages/index.html.erb
<div class="container-fluid">
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    あなたの<strong>感謝の気持ち</strong>をください
    <% if params[:a_user_id].present? %>
      <%#= link_to personality_insights_user_path(params[:a_user_id]), remote: true, data: { toggle: :'modal', target: :'.format-modal-lg' } do %>
<!--        <i class="fa fa-search" aria-hidden="true"></i>-->
      <%# end %>

      <%= link_to dashboards_user_path(params[:a_user_id]), remote: true, data: { toggle: :'modal', target: :'.format-modal-lg' } do %>
        <i class="fa fa-bar-chart" aria-hidden="true"></i>
      <% end %>
    <% else %>
      ♡
    <% end %>
  </div>


  <% if (link_to_next_page @messages, 'next') != nil %>
    <div class="pagination">
      <%= link_to_next_page @messages, 'next' %>
    </div>
  <% end %>

  <div id="messages" class="row row-flex row-flex-wrap">
    <% @messages.each_with_index do |message, i| %>
      <div class="col-lg-4 col-md-6 col-sm-6 flex-col grid-item">
        <%= render 'messages/message', { message: message } %>
      </div>
    <% end %>
  </div>

  <div class="page-load-status">
    <div class="loader-ellips infinite-scroll-request">
      <span class="loader-ellips__dot"></span>
      <span class="loader-ellips__dot"></span>
      <span class="loader-ellips__dot"></span>
      <span class="loader-ellips__dot"></span>
    </div>
    <p class="infinite-scroll-last">End of content</p>
    <p class="infinite-scroll-error">No more pages to load</p>
  </div>
</div>

<%= content_for :page_javascript do %>
  <script type="text/javascript" charset="utf-8">
    var $messages = $('#messages');
    var $grid = $messages.masonry({
      itemSelector: '.grid-item',
      percentPosition: true,
      stagger: 30,
      // nicer reveal transition
      visibleStyle: {transform: 'translateY(0)', opacity: 1},
      hiddenStyle: {transform: 'translateY(100px)', opacity: 0},
    });

    // get Masonry instance
    var msnry = $grid.data('masonry');

    if ($('.pagination').length > 0) {
      $grid.infiniteScroll({
        path: 'a[rel=next]',
        append: '.col-lg-4.col-md-6.col-sm-6.flex-col.grid-item',
        history: false,
        hideNav: '.pagination',
        outlayer: msnry,
        status: '.page-load-status',
      });
    }

    $(document).on('turbolinks:load', function() {
      $('.selectpicker').selectpicker();
    });

    <% if user_signed_in? %>
    $messages.on('click', '.js-like-button', function(e) {
      e.preventDefault();

      var $heart = $(this).find('img');
      var $likeSum = $(this).find('.js-like-sum');
      var $message_id = $(this).data('message-id');
      like_function($message_id, $(this), $heart, $likeSum);
    });

    function like_function(id, button, heart, sum) {
      button.removeClass('js-like-button');
      if (button.hasClass('decrement')) {
        $.ajax({url: '/likes/' + id, type: 'delete', data: {dataType: 'json'}}).done(function(data) {
          button.removeClass('decrement').addClass('increment').addClass('js-like-button');
          heart.attr('src', "<%= image_path('icon_heart.svg') %>");
          sum.text(data['count']);
        });
      } else {
        $.ajax({url: '/likes', type: 'post', data: {message_id: id, dataType: 'json'}}).done(function(data) {
          button.removeClass('increment').addClass('decrement').addClass('js-like-button');
          heart.attr('src', "<%= image_path('icon_heart_red.svg') %>");
          sum.text(data['count']);
        });
      }
    }
    <% end %>
  </script>
<% end %>

app/views/messages/new.html.erb
<%= form_for(Message.new, url: messages_path, remote: true) do |f| %>
  <%= f.hidden_field :sender_id, value: current_user.id %>
  <div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>

    <h4>
      メッセージ追加
    </h4>
  </div>

  <div class="modal-body">
    <div class="form-group">
      <div class="control-label">
        <label>送信相手</label>
      </div>

      <%
        option = @users.map do |user|
          if user.provider
            team_name = if user.team.present?
              "<b>@#{user.team}</b>"
            else
              ''
            end
            [user.name, user.id, { 'data-content': "<img class='img-circle profile-mini' src=#{user.image}> #{user.name} #{team_name}" }]
          else
            [user.email, user.id, { 'data-content': "<i class='fa fa-envelope fa-lg' aria-hidden='true'></i> #{user.email}" }]
          end
        end
      %>
      <%= select_tag :recipient_id,
        options_for_select(option, params['a_user_id']&.to_s),
        { prompt: "選択してください", class: "form-control selectpicker", data: { "live-search": true } }
      %>
    </div>

    <div class="form-group">
      <div class="control-label">
        <label>内容</label>
      </div>

      <%#= f.rich_text_area :body, class: 'form-control js-format-text', rows: '12', placeholder: 'Write your messages here' %>
      <%= f.rich_text_area :body, rows: '12', placeholder: 'Write your messages here' %>
    </div>
  </div>

  <div class="modal-footer modal-footer-center">
    <button type="button" class="btn btn-default" data-dismiss="modal">閉じる</button>
    <button class="btn btn-primary" type="submit" data-disable-with="処理中...">
      <i class="fa fa-send"></i>&nbsp;登録
    </button>
  </div>
<% end %>

<script type="text/javascript" charset="utf-8">
  $(function() {
    let $message_body = $('#message_body');
    let $new_message = $('#new_message');
    $message_body.on('keydown keyup keypress change', function() {
      localStorage.body = $('#message_body_trix_input_message').val();
      $('#new-message-icon').removeClass('fa-file-text-o').addClass('fa-pencil text-danger');
    });

    if (localStorage.body !== undefined) {
      $message_body.html('<div>' + localStorage.body + '</div>');
    }

    $new_message.on("submit", function() {
      localStorage.clear();
    });

    $('.selectpicker').selectpicker();
    $new_message.validate({
      rules: {
        'recipient_id': {
          required: true,
        },
        'message[body]': {
          required: true,
        },
      },
      messages: {
        'recipient_id': {
          required: '選択してください。',
        },
        'message[body]': {
          required: '必須入力です',
        },
      },
    });
  });
</script>